spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  application:
    name: OnlineStore
app:
  image:
    path: C:\Java_Projects\OnlineStore\images
web:
  frontend:
    address: http://localhost:3000